name: My First Workflow
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello
        run: echo Hello, world!
      - name: Print Double
        run: |
          echo "First output"
          echo "Second output"
      - name: Print bye
        run: echo Good Bye!
         
