name: My Second Workflow
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello
        run: echo Hello, world!
      - name: Prin bye
        run: echo Good Bye!
